version: 2
project_name: terraform-provider-rackdog
builds:
  - id: provider
    main: ./
    binary: terraform-provider-rackdog_v{{ .Version }}
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: ["-trimpath"]
archives:
  - id: zips
    builds: [provider]
    format: zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "SHA256SUMS"
signs:
  - artifacts: checksum
    signature: "${artifact}.sig"
    cmd: gpg
    args: ["--batch","--yes","--armor","--detach-sign","--local-user","{{ .Env.GPG_KEY_ID }}","--output","${signature}","${artifact}"]
release:
  draft: true

